### ISSUE TITLE
error in compile gauss_smooth.f90

### ISSUE THREAD

**Issue by Deg2v** [YoushanLiu/FDFK2D#1]
Hello, Professor Liu.

I am trying to use FDFK2D for some forward simulations. FDFK2D was compiled successfully.
But when I used `make` to compile gaus_mood in the `utils` folder, there were some errors as follows:
```
gfortran -O3 -Ofast -fopenmp -g -funroll-loops -malign-double -ffast-math -mtune=native -J. -I. -c gauss_smooth.f90 -o gauss_smooth.o
mkdir -p ~/bin
rm -rf ~/bin/gauss_smooth
gfortran -O3 -Ofast -fopenmp -g -funroll-loops -malign-double -ffast-math -mtune=native -J. -I. ./gauss_smooth.o  -o ~/bin/gauss_smooth
/usr/bin/ld: ./gauss_smooth.o: in function `get_parameter_':
/home/hzf/FDFK2D/utils/gauss_smooth.f90:463: undefined reference to `fseek_'
collect2: error: ld returned 1 exit status
make: *** [Makefile:57: all] Error 1
```
System: ubuntu 20.04
gfortran version: 10.5.0

**Comment by Deg2v** [comment]
Solved with 
```
! integer fseek, ftell 
integer ftell

! ier = fseek(iunit, 0, 2)
call fseek(iunit, 0, 2,ier)
```

**Comment by YoushanLiu** [comment]
@Deg2v Thank you for your interest in FDFK2D. The functions of fseek is defined differently in the Intel and GNU Fortran Compilers. The presented gauss_smooth is an implementation of the Intel Fortran compiler.
In the intel Fortran compiler, the fseek is defined as a function, while it is defined as subroutine. Yes. It can be solved by changing its invoking from function to subroutine just as you done.
